insert into CAMINATA_ENTITY (id, numero, titulo, tipo, fecha, departamento, ciudad, DURACION_ESTIMADA_MINUTOS, hora, DTYPE) values (1, 1, 'Eremogone', 'Eremogone Fenzl', '2024-08-17', 'San Andrés y Providencia', 'Santa Marta', 1, '12:15:00', 'Twitterworks');
insert into CAMINATA_ENTITY (id, numero, titulo, tipo, fecha, departamento, ciudad, DURACION_ESTIMADA_MINUTOS, hora, DTYPE) values (2, 2, 'Map Lichen', 'Rhizocarpon viridiatrum (Wulfen) Körb.', '2024-05-15', 'Sucre', 'Villavicencio', 4, '22:05:30', 'Yambee');
insert into CAMINATA_ENTITY (id, numero, titulo, tipo, fecha, departamento, ciudad, DURACION_ESTIMADA_MINUTOS, hora, DTYPE) values (3, 3, 'Taw Manroot', 'Marah watsonii (Cogn.) Greene', '2024-04-14', 'Putumayo', 'Armenia', 9, '18:10:55', 'Wikivu');
insert into CAMINATA_ENTITY (id, numero, titulo, tipo, fecha, departamento, ciudad, DURACION_ESTIMADA_MINUTOS, hora, DTYPE) values (4, 4, 'Eastern Pasqueflower', 'Pulsatilla patens (L.) Mill. ssp. patens (L.) Mill. [excluded]', '2025-02-18', 'Cauca', 'Bucaramanga', 6, '18:10:55', 'Twinte');
insert into CAMINATA_ENTITY (id, numero, titulo, tipo, fecha, departamento, ciudad, DURACION_ESTIMADA_MINUTOS, hora, DTYPE) values (5, 5, 'Drops-of-gold', 'Prosartes hookeri Torr. var. hookeri', '2025-01-09', 'Huila', 'Sincelejo', 2, '12:15:00', 'Youbridge');
insert into CAMINATA_ENTITY (id, numero, titulo, tipo, fecha, departamento, ciudad, DURACION_ESTIMADA_MINUTOS, hora, DTYPE) values (6, 6, 'Mediterranean Pepperweed', 'Lepidium hirtum (L.) Sm., nom. inq.', '2024-04-05', 'Norte de Santander', 'Ibagué', 5, '08:30:45', 'Bubblebox');
insert into CAMINATA_ENTITY (id, numero, titulo, tipo, fecha, departamento, ciudad, DURACION_ESTIMADA_MINUTOS, hora, DTYPE) values (7, 7, 'Pale Giant Hyssop', 'Agastache pallida (Lindl.) Cory', '2024-09-01', 'Arauca', 'Cúcuta', 2, '18:10:55', 'Skimia');
insert into CAMINATA_ENTITY (id, numero, titulo, tipo, fecha, departamento, ciudad, DURACION_ESTIMADA_MINUTOS, hora, DTYPE) values (8, 8, 'Leafy Desertdandelion', 'Malacothrix foliosa A. Gray', '2025-01-28', 'Santander', 'Montería', 2, '22:05:30', 'Camimbo');
insert into CAMINATA_ENTITY (id, numero, titulo, tipo, fecha, departamento, ciudad, DURACION_ESTIMADA_MINUTOS, hora, DTYPE) values (9, 9, 'Bog Birch', 'Betula pumila L. var. glandulifera Regel', '2025-02-20', 'Boyacá', 'Sincelejo', 4, '18:10:55', 'Yata');
insert into CAMINATA_ENTITY (id, numero, titulo, tipo, fecha, departamento, ciudad, DURACION_ESTIMADA_MINUTOS, hora, DTYPE) values (10, 10, 'Forest Sandalwood', 'Santalum freycinetianum Gaudich. var. freycinetianum', '2024-11-09', 'Santander', 'Santa Marta', 6, '08:30:45', 'Thoughtsphere');

TRUNCATE TABLE caminata RESTART IDENTITY;